### ISSUE TITLE
Pagination w/ Arrows, Ellipsis, Disabled

### ISSUE THREAD

**Issue by timbuckingham** [Fastspot/Boilerplate#10]
Can we update the pagination.twig file to include left/right arrows and ellipsis for when there are too many shown? Also disabled and selected states. I don't think the twig necessarily needs to reflect real data, so if it's always 5 pages shown or something that's fine.

The code from FKCC looks like it would be fine as boilerplate, though maybe not using "dots" for the modifier but rather something like pagination_ellipsis:

```
<div class="pagination{% if theme %} theme_{{theme}}{% endif %}">
	<a class="pagination_arrow pagination_arrow_left pagination_arrow_disabled" href="#previous">Previous</a>
	<span class="pagination_number_link pagination_number_selected">1</span>
	<a class="pagination_number_link" href="#2">2</a>
	<a class="pagination_number_link" href="#3">3</a>
	<a class="pagination_number_link" href="#4">4</a>
	<a class="pagination_number_link" href="#5">5</a>
	<span class="pagination_number_link dots">…</span>
	<a class="pagination_arrow pagination_arrow_right" href="#next">Next</a>
</div>
```

**Comment by nhall** [comment]
Yes, this is great. I'll update out twig file.

**Comment by nhall** [comment]
This has been included in the Boilerplate.
https://github.com/Fastspot/Boilerplate/commit/ff59feae0660ced0c58cd7e126b1f141dceeadf1
