### ISSUE TITLE
Automatic support for BigTree bar with sticky headers

### ISSUE THREAD

**Issue by jemaleddin** [Fastspot/Boilerplate#20]
Seems like every site we do has a sticky header and the BigTree admin bar is a known quantity in terms of height, etc. Is there a way to update the CSS of the bar itself OR add something to the boilerplate so that this always works across projects? Flexbox? Grid? Some kind of standard class name we can apply to sticky headers?

**Comment by nhall** [comment]
@jemaleddin,

Added. https://github.com/Fastspot/Boilerplate/commit/cb718d9644f5a27f29867aed7cb9d1208e211630

We can discuss on Friday.

Nick
