### ISSUE TITLE
Main Nav Partial Header

### ISSUE THREAD

**Issue by timbuckingham** [Fastspot/Boilerplate#25]
When "header" is true in navigation/main.twig and "title" is present, it draws this markup:

```
<div class="{{class}}_header">
	<h2 class="{{class}}_title">{{title}}</h2>
</div>
```
{{class}} doesn't appear to be used in the file, so I'm guessing this should really be main_nav_header and main_nav_title.

**Comment by nhall** [comment]
That is correct, I will fix
