### ISSUE TITLE
Update to npm pa11y 5.0.x

### ISSUE THREAD

**Issue by nhall** [Fastspot/Boilerplate#28]
[WCAG 2.1](https://www.w3.org/TR/WCAG21/) introduced new success criteria. We are going to need to update pa11y at some point. I know they've [documented migration](https://github.com/pa11y/pa11y/blob/master/MIGRATION.md#migrating-from-40-to-50) but it seems like a big task. I'd like to help you with this but since you are the man who put this plan into action it's going to start with you.

**Comment by mimoduo** [comment]
Updated
