### ISSUE TITLE
Handle Partials as Buttons

### ISSUE THREAD

**Issue by timbuckingham** [Fastspot/Boilerplate#29]
Shouldn't the handle.twig and search-handle.twig files really be drawing <button> tags rather than <a> tags that aren't really links?

**Comment by nhall** [comment]
I'd like to keep these drawing links. handle.twig works fine, it should like to the id of the menu elsewhere on the page. I think that's the ideal fallback. The search button should do the similar but link to the search page. I've updated the search handle to link to search template.

Thanks!

**Comment by timbuckingham** [comment]
That makes sense to me!
