### ISSUE TITLE
Background Video Support

### ISSUE THREAD

**Issue by timbuckingham** [Fastspot/Boilerplate#33]
https://github.com/Fastspot/Boilerplate/blob/master/src/twig/partials/background-video.twig

Since we no longer use Ogg, WebM, or YouTube files, I think it would make sense to drop the "sources" data for just a simpler "video" field which puts the MP4 into the proper background options location.

**Comment by nhall** [comment]
I have this on my branch:

https://github.com/Fastspot/Boilerplate/commit/ea317a45629399e87f27b234e5b036c83fe007c0
